version: '2.0'

services:
  api-pessoa:
    depends_on: 
      app_db:
        condition: service_healthy
    ports:
      - "8083:80"
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
  app_db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: app_db
    environment:
      - MSSQL_SA_PASSWORD=senhaforte@123
      - ACCEPT_EULA=Y
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-Psenhaforte@123", "-Q", "select 1"]
      interval: 5s
      timeout: 5s
      retries: 55
    ports:
     - "1450:1433"
    volumes:
      - c:\dados\volumes\mssql:/var/opt/mssql/data
 