version: '3.4'

networks:
  dev:
    driver: bridge   

services:
  api-pessoa:
    depends_on: 
     - "app_db"
    ports:
      - "8083:80"
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
  app_db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: app_db
    environment:
      - SA_PASSWORD=senhaforte@123
      - ACCEPT_EULA=Y
    ports:
     - "1450:1433"
    volumes:
      - c:\dados\volumes\mssql:/var/opt/mssql/data
 